/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */
#include <stdlib.h>
#include <t89c51cc02.h>
#include <mytypes.h>
#include <isrvectors.h>
#include <stdio.h>
#include <sysCfg.h>
#include <usart.h>
#include <timer0.h>
#include <timer1.h>
#include <pca.h>
#include <ledtable.h>
#include <adc.h>
#include <io.h>

VAR(BIT, bTimeOut, ) = 0;

void Tmr0MyIsr(void);

void main(void)
{
	VAR(__u32, u32TimeCntr, XDATA) = 0;
	VAR(__u8, Stunden, XDATA) = 0;
	VAR(__u8, Minuten, XDATA) = 0;
	VAR(__u8, Sekunden, XDATA) = 0;
	//Systeminitialisierung
	SysInit(10000000, X2_ON);

	//Interruptvektorsystem initialisieren
	IsrInit();

	//Timer initialisieren
	Tmr0Init(Tmr16Bit , TmrTimer);
	isrFncTmr0 = Tmr0MyIsr;
	Tmr0SetTime(1000);
	Tmr0IsrEna();
	Tmr0Run();
	IsrGlobalEna();

	//serielle Schnittstelle initialisieren
	UsartInit();
	UsartSetBaudrate(9600);
	UsartRecEna();
	

	printf_tiny("\r\nStarting Application-Loop\r\n");
	IoWritePort(P1, IoReadPort(P1) & 0x0F);
	while (1)
	{
		Sekunden = (__u8) u32TimeCntr % 60;
		Minuten = (__u8) (u32TimeCntr / 60) % 60;
 		Stunden = (__u8) (u32TimeCntr / 3600) % 24;
 		printf_fast ("Uhrzeit: %02d:%02d:%02d\r",
 				Stunden, Minuten, Sekunden);
 		u32TimeCntr++;
 		IoWriteBit(P1, 4, (u32TimeCntr & 0x01));
		while (!bTimeOut);
		bTimeOut = 0;

	}
}

void Tmr0MyIsr(void)
{
	static __u8 Wert;
	Wert++;
	bTimeOut = 1;
	IoWriteBit(P1, 5, (Wert & 0x01));
}
