
## Created by Anjuta
CODESIZE = 0x4000
IRAMSIZE = 0x0100
XRAMSIZE = 0x0100
XRAMLOC = 0x0000
CODELOC = 0x0000

MODEL = small
OPTIMIZE = speed

CC = sdcc
#DEBUG = --debug
DEBUG = 
CFLAGS = --model-$(MODEL)  $(DEBUG) \
		 --iram-size $(IRAMSIZE) --xram-size $(XRAMSIZE) --code-size $(CODESIZE) \
		 --xram-loc $(XRAMLOC) --code-loc $(CODELOC) \
		 --opt-code-$(OPTIMIZE)
##		 

INCFLAGS = -I../include/
LDFLAGS = --verbose --model-$(MODEL) --debug
LIBS = ../lib/t89c51cc02_$(MODEL).lib

%.rel: %.c
	$(CC) -c $(CFLAGS) $< $(INCFLAGS)
