
include ../Makefile.rules

all: clean

clean:
	rm -f core *~ \#* *.asm *.cdb *.rel *.hex *.ihx *.lst *.map \
		*.rst *.sym *.lnk *.lib *.bin *.adb *.mem *.dump* *.bak

.PHONY: all
.PHONY: count
.PHONY: clean
